# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - git clone https://github.com/dotnet/docfx/archive/v2.56.6.zip
    - unzip v2.56.6
    - ls
    - pwd

script:
#    - hugo -d blog
    - echo 'Hugo building!'
after_success:
    - echo 'Hugo build done!'
    # - git config --global user.email "allenforuse@gmail.com"
    # - git config --global user.name "justforuse"
    # - git clone https://$GITHUB_TOKEN@github.com/justforuse/justforuse.github.io.git container
    # - rm -rf container/blog
    # - cp -r blog container 
    # - cd container
    # - ls
    # - git add .
    # - git commit -m 'Travis upate blog'
    # - git push -u origin master